import { Product } from './data.service';
export const products: Product[] = [
  {
    id: '1',
    title: 'Mint',
    description: 'Mint makes a great garnish for summertime drinks, fruit platters and frozen desserts.' +
    ' It\'s excellent when paired with lamb and is found in many Middle Eastern, Thai and Vietnamese dishes. ',
    image: '../../assets/img/products/mint.jpg',
    tags: ['herbs', 'mint', 'restaurant', 'fresh'],
    featured: true,
    supplierId: '9dMXV3fXQKeL6hnkkBMZ5VqcANF2',
    category : 'Cooking Vegatables',
    appearance : 'Oval, bright green leaves with toothed edges and a rough, slightly fuzzy texture',
    flavor : 'Sweet, fresh, tingly; peppermint has a sharper, more menthol flavor, and spearmint is more delicate and sweet',
    size : '',
    color : 'Bright green',
    shape : 'Oval to almond-shaped leaves',
    commonlyCooked : 'Yes',
    servedRaw : 'Yes',
    availability : 'Year-round'
  },
  {
    id: '2',
    title: 'Thyme',
    description: 'Thyme has a clove-like taste that enhances Creole and Cajun dishes.' +
    ' It can also be used to season meat and in poultry stuffing. Its strong flavor requires sparing use.',
    image: '../../assets/img/products/thyme.jpg',
    tags: ['herbs', 'italian', 'thyme' , 'restaurant'],
    featured: true,
    supplierId: '9dMXV3fXQKeL6hnkkBMZ5VqcANF2',
    category : 'Cooking Vegetables',
    appearance : 'Tiny round green leaves on thin woody stems',
    flavor : 'A woodsy, spicy, clove and lemon-like flavor',
    size : 'Tiny leaves on slender woody stems',
    color : 'Bright to gray-green',
    shape : 'Tiny round leaves on woody stems',
    commonlyCooked : 'Yes',
    servedRaw : 'Yes',
    availability : 'Year-round'
  },
  {
    id: '5',
    title: 'Basil',
    description: 'Basil works well with tomatoes, squash, cabbage, beans, pasta, poultry, pesto or spaghetti sauce, pizza or seafood.' +
    ' Handle it with care as its leaves are delicate. Basil blends well with garlic, lemon, fennel, marjoram, oregano, thyme and curry.',
    image: '../../assets/img/products/basil.jpg',
    tags: ['herbs', 'restaurant', 'italian', 'basil'],
    featured: false,
    supplierId: '9dMXV3fXQKeL6hnkkBMZ5VqcANF2',
    category : 'Cooking Vegetables',
    appearance : 'Heart-shaped bright green leaves on a slender central stem',
    flavor : 'Slightly peppery or spicy, with warm, sweet notes',
    size: 'Basil leaves can be about half an inch to four inches long',
    color : 'Vibrant green',
    shape : 'Heart-shaped leaves',
    commonlyCooked : 'Yes',
    servedRaw : 'Yes',
    availability : 'Year-Round'
  },
  {
    id: '6',
    title: 'Parsley',
    description: 'Italian parsley differs from its curly cousin in that its leaves are flat, toothed and grouped in clusters' +
    ' of three on slender branches attached to a central stem or stalk (it is also known as flat-leaf parsley).',
    image: '../../assets/img/products/parsley.jpg',
    tags: ['herbs', 'parsley', 'restaurant', 'meditarian'],
    featured: false,
    supplierId: '9dMXV3fXQKeL6hnkkBMZ5VqcANF2',
    category : 'Cooking Vegetables',
    appearance : 'Green and multi-branched; branches divided in three sections with multiple leaves growing from the stems',
    flavor : 'Robust, somewhat peppery flavor',
    size: 'Parsley can grow up to a foot tall',
    color : 'Bright green',
    shape : 'Triangular, flat, deeply toothed leaves',
    commonlyCooked : 'Yes',
    servedRaw : 'Yes',
    availability : 'Year-Round'
  },
  {
    id: '3',
    title: 'Bell pepper',
    description: 'Bell peppers, whether they be green, red or yellow, are a staple in many homes.' +
    ' Encourage the purchase of organic bell peppers in your department to boost the bottom line as their sales are growing',
    image: '../../assets/img/products/bellpepper.jpg',
    tags: ['pepper', 'sweet', 'red', 'yellow', 'green', 'bell'],
    featured: true,
    supplierId: '9dMXV3fXQKeL6hnkkBMZ5VqcANF2',
    category : 'Cooking Vegetables, Salad Vegetables',
    appearance : 'Commonly Red/Green/Orange/Yellow with a thick green stem; blocky or bell-shaped with three to four lobes',
    flavor : 'Sweet and mild',
    size : 'A typical bell pepper can weigh ¼ to 1 pound, including the stem and seeds',
    color : 'There are varieties of Bell Peppers, each with its own accent. Common collors are: Red, Green, Orange and Yellow',
    shape : 'Blocky or bell-shaped, with three to four lobes',
    commonlyCooked : 'Yes',
    servedRaw : 'Yes',
    availability : 'Year-Round'
  },
  {
    id: '4',
    title: 'Anaheim pepper',
    description: 'Anaheim peppers are best known for being the type of peppers used in canned green chilis. They are ' +
    ' long and narrow and come in either red or green varieties. Green anaheims are a mild, sweet pepper, and are available year-round.',
    image: '../../assets/img/products/scorpion.jpg',
    tags: ['Anaheim', 'pepper', 'chili', 'mild', 'sweet'],
    featured: false,
    supplierId: '9dMXV3fXQKeL6hnkkBMZ5VqcANF2',
    category : 'Cooking Vegetables, Salad Vegetables',
    appearance : 'Long, narrow, glossy green or red pepper',
    flavor : 'Mild and sweet when green, slightly spicy when red',
    size : 'About 4-10 inches long',
    color : 'Glosse green or red',
    shape : 'Long, narrow, slightly curved',
    commonlyCooked : 'Yes',
    servedRaw : 'Yes',
    availability : 'Year-round; red anaheims are available in the summer.'
  },
  {
    id: '7',
    title: 'Jalapeno pepper',
    description: 'Jalapenos vary from dark green to red when fully mature with smooth, shiny skin.' +
    ' They have a vegetal flavor with a mild to medium spice level ranging from 2,000 to 10,000 Scoville units.',
    image: '../../assets/img/products/jalapeno.jpg',
    tags: ['pepper', 'medium', 'hot', 'jalapeno'],
    featured: true,
    supplierId: '9dMXV3fXQKeL6hnkkBMZ5VqcANF2',
    category : 'Cooking Vegetables, Salad Vegetables',
    appearance : 'Smaller, conical, slightly curved pepper with smooth, shiny dark green to red skin',
    flavor : 'Vegetal and spicy; mature red peppers have a sweeter flavor',
    size : 'About 2-3 inches long, with stems of about 1 inch long',
    color : 'Dark green to red',
    shape : 'Conical, slightly curved',
    commonlyCooked : 'Yes',
    servedRaw : 'Yes',
    availability : 'Year-Round'
  },
  {
    id: '8',
    title: 'Habanero pepper',
    description: 'Habanero peppers are small, lantern-shaped, shiny and most commonly orange in color.' +
    ' They\'ve very hot, at about 200,000 to 300,000 Scoville units, with a somewhat fruity flavor and fragrance.',
    image: '../../assets/img/products/habanero.jpg',
    tags: ['pepper', 'orange', 'hot'],
    featured: false,
    supplierId: '9dMXV3fXQKeL6hnkkBMZ5VqcANF2',
    category : 'Cooking Vegetables, Salad Vegetables',
    appearance : 'Shiny, lantern-shaped orange peppers about 2 inches long',
    flavor : 'Fruity and spicy, at about 200,000 to 300,000 Scoville units',
    size : 'About 2 inches long and a little less than 2 inches wide',
    color : 'ypically bright orange',
    shape : 'Lantern-shaped',
    commonlyCooked : 'Yes',
    servedRaw : 'Yes',
    availability : 'Year-Round'
  }
];
