import { User } from './data.service';

export const users: User[] = [
  {
    id: '2doBbUNZtEcqsuPIRxe4Wfc7Z9C3',
    isSupplier: false,
    lastName: 'Doe',
    name: 'John',
    email: 'johndoe@gmail.com',
    favorites: ['3'],
    quotationsReceived: [],
    quotationsSent: [],
    tendersReceived: [],
    tendersSent: []
  },
  {
    id: '9dMXV3fXQKeL6hnkkBMZ5VqcANF2',
    email: 'pickerfarm@gmail.com',
    title: 'Picker Farm',
    description: '',
    category: '',
    subCategory: '',
    favorites: [],
    featured: true,
    image: '',
    isSupplier: true,
    lastName: 'Farm',
    name: 'Picker',
    quotationsReceived: [],
    quotationsSent: [],
    tags: ['pepper'],
    tendersReceived: [],
    tendersSent: []
  },
  {
    id: '2',
    email: '',
    title: 'fresh foods',
    description: '',
    category: '',
    subCategory: '',
    favorites: [],
    featured: true,
    image: '',
    isSupplier: true,
    lastName: '',
    name: '',
    quotationsReceived: [],
    quotationsSent: [],
    tags: [],
    tendersReceived: [],
    tendersSent: []
  },
  {
    id: '3',
    email: '',
    title: 'Trini Produce',
    description: '',
    category: '',
    subCategory: '',
    favorites: [],
    featured: true,
    image: '',
    isSupplier: true,
    lastName: '',
    name: '',
    quotationsReceived: [],
    quotationsSent: [],
    tags: [],
    tendersReceived: [],
    tendersSent: []
  },
  {
    id: '4',
    email: '',
    title: 'The right foods',
    description: '',
    category: '',
    subCategory: '',
    favorites: [],
    featured: true,
    image: '',
    isSupplier: true,
    lastName: '',
    name: '',
    quotationsReceived: [],
    quotationsSent: [],
    tags: [],
    tendersReceived: [],
    tendersSent: []
  }
];
